services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    #ports:
    #  - "${POSTGRES_PORT}:5432"
    expose:
      - 5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
